-- ============================================================
-- Dibal — target schema
--
-- This file is the AUTHORITATIVE SPECIFICATION, not a migration.
-- Build EF Core entities and configurations that produce this schema,
-- then generate migrations with `dotnet ef migrations add`.
-- Do not run this file directly against the database.
--
-- Tables are created in the phase indicated by the comment above each.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS citext;

-- ------------------------------------------------------------
-- Enums
-- ------------------------------------------------------------
CREATE TYPE customer_type   AS ENUM ('Reseller', 'EndUser');
CREATE TYPE size_band       AS ENUM ('Kg6To15', 'Kg15To30');
CREATE TYPE stock_status    AS ENUM ('InStock', 'Allocated', 'Delivered',
                                     'Returned', 'Faulty', 'WrittenOff');
CREATE TYPE movement_type   AS ENUM ('Receipt', 'Allocation', 'Deallocation',
                                     'Delivery', 'Return', 'Adjustment', 'WriteOff');
CREATE TYPE delivery_status AS ENUM ('Draft', 'Confirmed', 'Dispatched', 'Cancelled');
CREATE TYPE document_type   AS ENUM ('DeliveryNote', 'WarrantyCertificate');
CREATE TYPE outbox_status   AS ENUM ('Pending', 'Sending', 'Sent', 'Failed');

-- Returned / Faulty / Return are reserved for a future RMA feature.
-- They are intentionally unused in v1. Do not remove them.


-- ============================================================
-- PHASE 0 — audit and settings
-- ============================================================

-- Written by an EF Core SaveChanges interceptor. Append-only.
CREATE TABLE audit_log (
    id           bigserial    PRIMARY KEY,
    entity_name  text         NOT NULL,
    entity_id    text         NOT NULL,
    action       text         NOT NULL,          -- Insert | Update | Delete
    before       jsonb,
    after        jsonb,
    changed_by   uuid,
    changed_at   timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_entity ON audit_log (entity_name, entity_id, changed_at DESC);
CREATE INDEX ix_audit_changed_at ON audit_log (changed_at DESC);

-- Singleton row. Enforced by the check constraint.
CREATE TABLE app_settings (
    id                     smallint    PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    company_name           text        NOT NULL DEFAULT '',
    company_address        text        NOT NULL DEFAULT '',
    company_phone          text,
    company_email          text,
    logo_storage_key       text,
    document_prefix        text        NOT NULL DEFAULT 'DN',
    low_stock_threshold    int         NOT NULL DEFAULT 5,
    smtp_host              text,
    smtp_port              int         NOT NULL DEFAULT 587,
    smtp_use_starttls      boolean     NOT NULL DEFAULT true,
    smtp_username          text,
    smtp_password_enc      text,                  -- Data Protection encrypted. NEVER plaintext.
    smtp_from_name         text,
    smtp_from_address      text,
    smtp_reply_to          text,
    modified_at            timestamptz NOT NULL DEFAULT now(),
    modified_by            uuid
);

-- The singleton row must exist before anything reads it. `stock_levels`
-- subqueries app_settings for the low-stock threshold, so with no row every
-- model's threshold is NULL. The initial migration seeds this.
INSERT INTO app_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ASP.NET Core Identity tables are generated by EF Core. Roles: Owner, Manager, Staff.


-- ============================================================
-- PHASE 1 — clients
-- ============================================================

CREATE TABLE clients (
    id                  uuid          PRIMARY KEY,
    business_name       text          NOT NULL,
    client_name         text,
    address_line1       text,
    address_line2       text,
    city                text,
    county              text,
    postcode            text,
    postcode_normalised text GENERATED ALWAYS AS
                            (upper(replace(coalesce(postcode, ''), ' ', ''))) STORED,
    email               citext,
    phone               text,
    customer_type       customer_type NOT NULL,
    notes               text,
    is_deleted          boolean       NOT NULL DEFAULT false,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    created_by          uuid          NOT NULL,
    modified_at         timestamptz   NOT NULL DEFAULT now(),
    modified_by         uuid          NOT NULL
);

CREATE INDEX ix_clients_business_trgm ON clients USING gin (business_name gin_trgm_ops);
CREATE INDEX ix_clients_client_trgm   ON clients USING gin (client_name gin_trgm_ops);
CREATE INDEX ix_clients_postcode      ON clients (postcode_normalised);
CREATE INDEX ix_clients_active        ON clients (business_name) WHERE NOT is_deleted;


-- ============================================================
-- PHASE 2 — stock
-- ============================================================

CREATE TABLE scale_models (
    id                  uuid        PRIMARY KEY,
    name                text        NOT NULL,
    size_band           size_band   NOT NULL,
    description         text,
    low_stock_threshold int,                       -- NULL = use app_settings global
    is_active           boolean     NOT NULL DEFAULT true,
    is_deleted          boolean     NOT NULL DEFAULT false,
    created_at          timestamptz NOT NULL DEFAULT now(),
    created_by          uuid        NOT NULL,
    modified_at         timestamptz NOT NULL DEFAULT now(),
    modified_by         uuid        NOT NULL
);

-- Uniqueness must ignore soft-deleted rows. A plain UNIQUE would let a
-- soft-deleted model reserve its name forever, so re-creating a model
-- deleted by mistake would fail with a constraint violation the UI cannot
-- explain. Same reasoning applies to serials below.
CREATE UNIQUE INDEX uq_scale_models_name
    ON scale_models (name) WHERE NOT is_deleted;

CREATE TABLE goods_in_batches (
    id            uuid        PRIMARY KEY,
    reference     text,
    supplier_name text        NOT NULL DEFAULT 'Dibal',
    received_date date        NOT NULL,
    notes         text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    created_by    uuid        NOT NULL
);

CREATE TABLE stock_units (
    id                  uuid         PRIMARY KEY,
    model_id            uuid         NOT NULL REFERENCES scale_models(id),
    serial_no           text         NOT NULL,
    status              stock_status NOT NULL DEFAULT 'InStock',
    goods_in_batch_id   uuid         REFERENCES goods_in_batches(id),
    received_date       date         NOT NULL,
    current_delivery_id uuid,                      -- FK added after deliveries exists
    notes               text,
    is_deleted          boolean      NOT NULL DEFAULT false,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    created_by          uuid         NOT NULL,
    modified_at         timestamptz  NOT NULL DEFAULT now(),
    modified_by         uuid         NOT NULL,

    -- Referenced by the composite FK on delivery_lines, which keeps that
    -- table's denormalised model_id honest. Redundant against the PK, but an
    -- FK target must be a full (non-partial) unique constraint.
    CONSTRAINT uq_stock_id_model UNIQUE (id, model_id)
);

-- Serial is unique PER MODEL, not globally. Serial lookup may return
-- multiple rows across models; the UI must show a result list.
--
-- Partial on is_deleted: a soft-deleted unit must not reserve its serial.
-- Re-receiving SN-1042 after a mis-keyed unit was soft-deleted is normal.
CREATE UNIQUE INDEX uq_stock_model_serial
    ON stock_units (model_id, serial_no) WHERE NOT is_deleted;

CREATE INDEX ix_stock_status      ON stock_units (status) WHERE NOT is_deleted;
CREATE INDEX ix_stock_model       ON stock_units (model_id, status);
CREATE INDEX ix_stock_serial_trgm ON stock_units USING gin (serial_no gin_trgm_ops);
CREATE INDEX ix_stock_delivery    ON stock_units (current_delivery_id);

-- Keyset pagination needs a stable total ordering (see 01-architecture.md).
-- deliveries has ix_deliveries_date for the same purpose.
CREATE INDEX ix_stock_keyset ON stock_units (created_at DESC, id DESC)
    WHERE NOT is_deleted;

-- APPEND-ONLY. Never UPDATE or DELETE. Corrections are compensating rows.
CREATE TABLE stock_movements (
    id                bigserial     PRIMARY KEY,
    unit_id           uuid          NOT NULL REFERENCES stock_units(id),
    movement_type     movement_type NOT NULL,
    from_status       stock_status,
    to_status         stock_status  NOT NULL,
    delivery_id       uuid,
    goods_in_batch_id uuid          REFERENCES goods_in_batches(id),
    reason            text,
    occurred_at       timestamptz   NOT NULL DEFAULT now(),
    performed_by      uuid          NOT NULL
);

CREATE INDEX ix_movements_unit ON stock_movements (unit_id, occurred_at DESC);
CREATE INDEX ix_movements_delivery ON stock_movements (delivery_id);


-- ============================================================
-- PHASE 3 — deliveries
-- ============================================================

CREATE TABLE deliveries (
    id                  uuid            PRIMARY KEY,
    reference_no        text            NOT NULL UNIQUE,
    client_id           uuid            NOT NULL REFERENCES clients(id),
    status              delivery_status NOT NULL DEFAULT 'Draft',
    purchase_date       date,

    -- Frozen copy of the client's details at confirmation time.
    -- Documents render from this, never from the live client row.
    client_snapshot     jsonb,

    default_warranty_end  date,
    default_support_start date,
    default_support_end   date,

    notes               text,
    confirmed_at        timestamptz,
    confirmed_by        uuid,
    cancelled_at        timestamptz,
    cancelled_by        uuid,
    cancellation_reason text,
    is_deleted          boolean         NOT NULL DEFAULT false,
    created_at          timestamptz     NOT NULL DEFAULT now(),
    created_by          uuid            NOT NULL,
    modified_at         timestamptz     NOT NULL DEFAULT now(),
    modified_by         uuid            NOT NULL,

    -- Cancelled is permitted without a snapshot because a Draft may be
    -- cancelled. Hard-deleting a delivery is forbidden (CLAUDE.md invariant 2),
    -- so cancellation is the only disposal route for an abandoned draft — and
    -- a draft never had a snapshot to freeze.
    CONSTRAINT ck_confirmed_has_snapshot
        CHECK (status IN ('Draft', 'Cancelled') OR client_snapshot IS NOT NULL)
);

CREATE INDEX ix_deliveries_client ON deliveries (client_id, purchase_date DESC);
CREATE INDEX ix_deliveries_status ON deliveries (status) WHERE NOT is_deleted;
CREATE INDEX ix_deliveries_date   ON deliveries (purchase_date DESC, id DESC);

ALTER TABLE stock_units
    ADD CONSTRAINT fk_stock_delivery
    FOREIGN KEY (current_delivery_id) REFERENCES deliveries(id);

-- Declared here for the same phase-ordering reason: stock_movements is created
-- in Phase 2, before deliveries exists.
ALTER TABLE stock_movements
    ADD CONSTRAINT fk_movements_delivery
    FOREIGN KEY (delivery_id) REFERENCES deliveries(id);

CREATE TABLE delivery_lines (
    id            uuid PRIMARY KEY,
    delivery_id   uuid NOT NULL REFERENCES deliveries(id),
    stock_unit_id uuid NOT NULL REFERENCES stock_units(id),
    model_id      uuid NOT NULL REFERENCES scale_models(id),  -- denormalised for reporting

    -- Defaulted from the delivery header, editable per line.
    warranty_end  date,
    support_start date,
    support_end   date,

    -- Support Valid/Expired is COMPUTED from support_end. Never stored.

    CONSTRAINT uq_line_delivery_unit UNIQUE (delivery_id, stock_unit_id),

    -- model_id is denormalised for reporting, so it can drift from the unit's
    -- actual model. This composite FK makes drift impossible at the database
    -- level rather than relying on the delivery builder to get it right.
    CONSTRAINT fk_line_unit_model
        FOREIGN KEY (stock_unit_id, model_id) REFERENCES stock_units (id, model_id)
);

CREATE INDEX ix_lines_delivery ON delivery_lines (delivery_id);
CREATE INDEX ix_lines_unit     ON delivery_lines (stock_unit_id);
CREATE INDEX ix_lines_support  ON delivery_lines (support_end);   -- expiry alerts

-- A unit can only sit on one active delivery. Enforced by
-- stock_units.current_delivery_id + status inside the allocation transaction.

-- Renewals EXTEND delivery_lines.support_end and log history here.
-- Never overwrite history.
CREATE TABLE support_renewals (
    id               uuid        PRIMARY KEY,
    delivery_line_id uuid        NOT NULL REFERENCES delivery_lines(id),
    previous_end     date,
    new_end          date        NOT NULL,
    note             text,
    renewed_at       timestamptz NOT NULL DEFAULT now(),
    renewed_by       uuid        NOT NULL
);

CREATE INDEX ix_renewals_line ON support_renewals (delivery_line_id, renewed_at DESC);

-- Gapless-ish reference numbering. Claim with SELECT ... FOR UPDATE.
CREATE TABLE delivery_counters (
    year        int PRIMARY KEY,
    last_number int NOT NULL DEFAULT 0
);


-- ============================================================
-- PHASE 4 — documents
-- ============================================================

-- IMMUTABLE. Never regenerate or overwrite an existing row's PDF.
CREATE TABLE documents (
    id            uuid          PRIMARY KEY,
    delivery_id   uuid          NOT NULL REFERENCES deliveries(id),
    document_type document_type NOT NULL,
    reference_no  text          NOT NULL,
    storage_key   text          NOT NULL,        -- R2 object key
    sha256        text          NOT NULL,
    byte_size     int           NOT NULL,
    generated_at  timestamptz   NOT NULL DEFAULT now(),
    generated_by  uuid          NOT NULL
);

CREATE INDEX ix_documents_delivery ON documents (delivery_id, generated_at DESC);


-- ============================================================
-- PHASE 5 — email
-- ============================================================

CREATE TABLE outbox_messages (
    id              bigserial     PRIMARY KEY,
    message_type    text          NOT NULL,
    payload         jsonb         NOT NULL,
    status          outbox_status NOT NULL DEFAULT 'Pending',
    attempts        int           NOT NULL DEFAULT 0,
    next_attempt_at timestamptz   NOT NULL DEFAULT now(),
    last_error      text,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    sent_at         timestamptz
);

-- 'Failed' is in this index so the UI can list failures and offer a manual
-- resend. It is NOT a licence to auto-retry them: Failed is terminal after 5
-- attempts, so OutboxProcessor's claim query MUST also filter `attempts < 5`.
-- Without that, dead messages are re-claimed on every 30s poll forever.
CREATE INDEX ix_outbox_pending ON outbox_messages (status, next_attempt_at)
    WHERE status IN ('Pending', 'Failed');

CREATE TABLE email_log (
    id                bigserial   PRIMARY KEY,
    outbox_message_id bigint      REFERENCES outbox_messages(id),
    document_id       uuid        REFERENCES documents(id),
    to_address        text        NOT NULL,
    subject           text        NOT NULL,
    succeeded         boolean     NOT NULL,
    error             text,
    attempted_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_email_log_document ON email_log (document_id, attempted_at DESC);


-- ============================================================
-- PHASE 6 — dashboard aggregates
-- ============================================================

CREATE MATERIALIZED VIEW stock_levels AS
SELECT
    m.id            AS model_id,
    m.name          AS model_name,
    m.size_band,
    count(*) FILTER (WHERE u.status = 'InStock')   AS in_stock,
    count(*) FILTER (WHERE u.status = 'Allocated') AS allocated,
    count(*) FILTER (WHERE u.status = 'Delivered') AS delivered,
    coalesce(m.low_stock_threshold,
             (SELECT low_stock_threshold FROM app_settings WHERE id = 1)) AS threshold
FROM scale_models m
LEFT JOIN stock_units u ON u.model_id = m.id AND NOT u.is_deleted
WHERE NOT m.is_deleted
GROUP BY m.id, m.name, m.size_band, m.low_stock_threshold;

CREATE UNIQUE INDEX ix_stock_levels_model ON stock_levels (model_id);
-- Refresh with REFRESH MATERIALIZED VIEW CONCURRENTLY on a schedule
-- and after goods-in / delivery confirmation.
